version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - ./config.json:/config.json:rw
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WATCHTOWER_CLEANUP
      - WATCHTOWER_RUN_ONCE
      - WATCHTOWER_MONITOR_ONLY
      - WATCHTOWER_NOTIFICATIONS
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD
#     networks:
#       - nginx-proxy-tier

# networks:
#   nginx-proxy-tier:
#     external: true
