version: "3"

services:
  nginx-react:
    container_name: nginx-react
    hostname: nginx-react
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_HOST
    # volumes:
    #   - ./build:/usr/share/nginx/html
    #   - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    # Mounting a volume in remote context expects to find build folder in same absolute path
    # as './build' folder expands to. There is no 'copy' command in docker compose although it is
    # often requested feature to add: https://github.com/docker/compose/issues/5523
    # Thus files need to be copied to remote in same absolute paths as they are in local.
    # However there may be premission problems in doing that if non-root SSH user is used.
    # To overcome that problem, use non-root SSH user to copy files to remote user's home folder and use
    # COPY or ADD commands in Dockerfile to copy files inside the docker container.
    networks:
      - nginx-proxy-tier
    expose:
      - "80"

networks:
  nginx-proxy-tier:
    external: true